services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rails_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_app_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rails_network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RUBYOPT: "-r logger" # устранения бага, см. README.md
      DATABASE_URL: postgresql://rails_app:password@db:5432/rails_app_dev
    networks:
      - rails_network

volumes:
  postgres_data:
  bundle_cache:

networks:
  rails_network:
    driver: bridge
